name: Build and upload

on:
  push:
    branches: [ "master" ]
    tags:
      - "v*"
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        BUILD_TARGET: [release] # refers to a cargo profile
        platform:
          - os-name: linux-x86_64
            runs-on: ubuntu-24.04
            target: x86_64-unknown-linux-musl

          - os-name: linux-aarch64
            runs-on: ubuntu-24.04-arm
            target: aarch64-unknown-linux-musl

          - os-name: macOS-x86_64
            runs-on: macOS-latest
            target: x86_64-apple-darwin

    runs-on: ${{ matrix.platform.runs-on }}
        
    steps:
    - uses: actions/checkout@v4
    - name: Cache
      uses: actions/cache@v4
      with:
        path: |
         ~/.cargo/registry
         ~/.cargo/git
         target
        key: ${{ runner.os }}-cargo-${{ matrix.BUILD_TARGET }}-${{ matrix.platform.runs-on }}-${{ hashFiles('**/Cargo.lock') }}
    - name: Build
      run: cargo build --profile ${{ matrix.BUILD_TARGET }}
    # - name: Run tests
    #   run: cargo test --verbose
    - uses: actions/upload-artifact@v4
      with:
        name: rust_kms-${{ matrix.platform.target }}
        path: target/release/rust_kms
        
